import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { HorizontalBox, Button,LineEdit, TextEdit,VerticalBox,ScrollView } from "std-widgets.slint";
import {I18n, Language} from "../i18n.slint";
import {UiWallets,TranxItem,TranxDay,TranxType,FavoriteAddr,ROOT-GLOBAL, WalletAccounts, ROOT-GLOBAL} from "../global.slint";
import {CreateWallet,ImportWallet, Contacts,Qrcode,MnemonicWin,Transaction, SecurityWin,About,
    XlineEdit,LanguageWin,NetworkWin,SendWin,DelContact,DelWallet,ErrorWin, RenameWallet} from "../components/index.slint";
import { PasswordView } from "./password.slint";


export component AccountsView inherits Rectangle {
    property <bool> show-select-wallet: false;
    property <int> active-index: 0;
    property <bool> show-conntacts: false;
    property <bool> show-settings: false;
    property <bool> show-tranx-block: false;
    property <bool> show-language: false;
    property <bool> show-network: false;
    property <bool> show-value: true;
    property <bool> show-create-win:false;
    property <bool> show-import-win:false;
    property <bool> show-add-contact:false;
    property <bool> show-qr-code:false;
    property <bool> show-mnemonic-words:false;
    property <bool> show-send-win:false;
    property <bool> show-password-check:false;
    property <bool> show-rename-wallet:false;
    property <string> mnemonic-words;
    property <string> edit-contact-name;
    property <string> edit-contact-address;
    property <int> edit-contact-index:0;
    property <TranxItem> tranx-item;
    background: ROOT_GLOBAL.bgColor2;
    i18n := I18n {
        lang <=> Language.name;
    }

    init => {
        WalletAccounts.current-address = UiWallets.ui-wallets[0].address;
        WalletAccounts.current-password = UiWallets.ui-wallets[0].password;
        WalletAccounts.current-balance = "0.00";
        WalletAccounts.fetch-history(WalletAccounts.is-test, UiWallets.ui-wallets[0].address);
    }
    account-view := Rectangle {
        y: header-bar.height;
        x: parent.width * 18%;
        width: parent.width * 82%;
        height: parent.height - header-bar.height;
        background: ROOT-GLOBAL.bgColorMask2;
        border-radius: 5px;
        HorizontalLayout {
            VerticalLayout {
                padding-left: 16px;
                padding-top: 16px;
                padding-right: 8px;
                padding-bottom: 16px;
                width: 54%;
                Rectangle {
                    height: 20%;
                    border-radius: 5px;
                    background: ROOT-GLOBAL.mainColor;
                    VerticalLayout {
                        padding-bottom: 5px;
                        padding-top: 5px;
                        padding-left: 10px;
                        padding-right: 10px;
                        HorizontalLayout {
                            height: 20%;
                            walletName := SText {
                                font-size: 30px;
                                font-weight: 800;
                                min-width: 400px;
                                text: UiWallets.ui-wallets[active-index].name;
                                color: ROOT-GLOBAL.bgColorMask2;
                            }

                            Rectangle { }

                            XButton {
                                font-size: 16px;
                                text: "";
                                height: 28px;
                                width: 28px;
                                icon: @image-url("../assets/account_tree.svg");
                                is-transparent: false;
                                show-icon: true;
                                round: true;
                                clicked => {
                                    root.show-select-wallet = true;
                                    select-wallet.x = root.width * 50%;
                                }
                            }
                        }

                        walletAddress := SText {
                            font-size: 16px;
                            font-weight: 600;
                            text: UiWallets.ui-wallets[active-index].address;
                            color: ROOT-GLOBAL.bgColorMask2;
                        }

                        HorizontalLayout {
                            // height: 30%;
                            XButton {
                                font-size: 16px;
                                text: "";
                                height: 28px;
                                width: 28px;
                                icon: @image-url("../assets/vpn_key.svg");
                                is-transparent: false;
                                show-icon: true;
                                round: true;
                                clicked => {
                                    WalletAccounts.gen-mnemonic-array(UiWallets.ui-wallets[active-index].mnemonic);
                                    show-password-check = true;
                                }
                            }

                            Rectangle {
                                width: 10px;
                            }

                            XButton {
                                font-size: 16px;
                                text: "";
                                height: 28px;
                                width: 28px;
                                icon: @image-url("../assets/visibility_off.svg");
                                is-transparent: false;
                                show-icon: true;
                                round: true;
                                clicked => {
                                    show-value = !show-value;
                                    if show-value {
                                        self.icon = @image-url("../assets/visibility_off.svg");
                                    } else {
                                        self.icon = @image-url("../assets/visibility.svg");
                                    }
                                }
                            }

                            Rectangle {
                                width: 10px;
                            }

                            XButton {
                                font-size: 16px;
                                text: "";
                                height: 28px;
                                width: 28px;
                                icon: @image-url("../assets/qr_code.svg");
                                is-transparent: false;
                                show-icon: true;
                                round: true;
                                clicked => {
                                    // WalletAccounts.current-address = UiWallets.ui-wallets[active-index].address;
                                    show-qr-code = true; // Show the QR code component
                                }
                            }

                            Rectangle { }

                            walletValue := SText {
                                visible: !WalletAccounts.fetching;
                                font-size: 16px;
                                font-weight: 800;
                                text: show-value ? WalletAccounts.current-balance + "  " + "XDAG" : "******  XDAG";
                                color: ROOT-GLOBAL.bgColorMask2;
                            }

                            if WalletAccounts.fetching == true: Image {
                                colorize: ROOT_GLOBAL.bgColorMask2;
                                source: @image-url("../assets/spinner.svg");
                                rotation-angle: !WalletAccounts.fetching ? 0deg : 240deg * animation-tick() / 1s;
                                animate rotation-angle {
                                    easing: ease-in-out;
                                    iteration-count: -1;
                                }
                            }
                        }
                    }
                }

                Rectangle {
                    height: 16px;
                    background: ROOT_GLOBAL.bgColorMask2;
                }

                Rectangle {
                    border-radius: 5px;
                    background: ROOT_GLOBAL.bgColor2;
                    VerticalLayout {
                        padding-bottom: 5px;
                        padding-top: 5px;
                        padding-left: 10px;
                        padding-right: 10px;
                        SText {
                            font-size: 20px;
                            font-weight: 800;
                            text: i18n.send;
                        }

                        SText {
                            font-size: 18px;
                            font-weight: 400;
                            text: i18n.to;
                        }

                        toAddress := XlineEdit {
                            lang-name <=> Language.name;
                            font-size: 16px;
                            placeholder-text: i18n.walletAddress;
                        }

                        SText {
                            font-size: 18px;
                            font-weight: 400;
                            text: i18n.amount;
                        }

                        Amount := XlineEdit {
                            lang-name <=> Language.name;
                            font-size: 24px;
                            height: 70px;
                            placeholder-text: "XDAG";
                            horizontal-alignment: center;
                            input-type: decimal;
                        }

                        SText {
                            font-size: 18px;
                            font-weight: 400;
                            text: i18n.remark;
                        }

                        Remark := XlineEdit {
                            lang-name <=> Language.name;
                            font-size: 16px;
                            placeholder-text: i18n.remark;
                            // text-edited => {
                            //     remarkLength.text = WalletAccounts.character-count(Remark.text)
                            // }
                        }

                        HorizontalBox {
                            alignment: end;
                            remarkLength := SText {
                                color: Remark.text.character-count > 32 ? ROOT_GLOBAL.redColor : Colors.whitesmoke; //WalletAccounts.remark-len-color;
                                font-size: 16px;
                                text: Remark.text.character-count;
                                //"0";
                            }

                            SText {
                                font-size: 16px;
                                text: " /  32";
                            }
                        }

                        HorizontalBox {
                            alignment: end;
                            continueBtn := Button {
                                height: 35px;
                                min-width: 100px;
                                primary: true;
                                text: i18n.continueText;
                                // enabled: toAddress.text != "" && Amount.text != "";
                                clicked => {
                                    if toAddress.text.is-empty {
                                        toAddress.focus-me();
                                        return;
                                    }
                                    if !Amount.text.is-float() || Amount.text.to-float() <= 0 {
                                        Amount.focus-me();
                                        return;
                                    }
                                    if Remark.text.character-count > 32 {
                                        Remark.focus-me();
                                        return;
                                    }
                                    WalletAccounts.sending = false;
                                    WalletAccounts.sent = false;
                                    show-send-win = true;
                                }
                            }
                        }
                    }
                }
            }

            VerticalLayout {
                width: 46%;
                padding-bottom: 16px;
                padding-left: 8px;
                padding-top: 16px;
                padding-right: 16px;
                Rectangle {
                    // height: 100%;
                    border-radius: 5px;
                    background: ROOT_GLOBAL.bgColor2;
                    VerticalBox {
                        alignment: start;
                        padding-bottom: 5px;
                        padding-top: 5px;
                        padding-left: 10px;
                        padding-right: 10px;
                        SText {
                            font-size: 24px;
                            font-weight: 800;
                            text: i18n.transactions;
                        }

                        Rectangle {
                            height: 10px;
                        }

                        if WalletAccounts.is-tranx-empty == true: VerticalLayout {
                            // width: 100%;
                            Rectangle {
                                height: 30px;
                            }

                            Rectangle {
                                if WalletAccounts.fetching == false: Image {
                                    width: 120px;
                                    colorize: ROOT_GLOBAL.bottomNavColor;
                                    source: @image-url("../assets/web_asset.svg");
                                }
                                if WalletAccounts.fetching == true: Image {
                                    colorize: ROOT_GLOBAL.bottomNavColor;
                                    width: 80px;
                                    source: @image-url("../assets/spinner.svg");
                                    rotation-angle: !WalletAccounts.fetching ? 0deg : 240deg * animation-tick() / 1s;
                                    animate rotation-angle {
                                        easing: ease-in-out;
                                        iteration-count: -1;
                                    }
                                }
                            }

                            Rectangle {
                                height: 50px;
                            }

                            Rectangle {
                                SText {
                                    font-size: 20px;
                                    font-weight: 800;
                                    min-width: 100px;
                                    horizontal-alignment: center;
                                    text: i18n.no_transactions;
                                }
                            }
                        }
                        if WalletAccounts.is-tranx-empty == false: ScrollView {
                            width: 100%;
                            height: 90%;
                            // vertical-scrollbar-policy: ScrollBarPolicy.always-off;
                            VerticalLayout {
                                alignment: start;
                                // height: 100%;
                                for day-item in WalletAccounts.tranx-model: VerticalLayout {
                                    SText {
                                        text: day-item.day;
                                        font-size: 17px;
                                        font-weight: 800;
                                    }

                                    Rectangle {
                                        height: 10px;
                                    }

                                    for item in day-item.item: HorizontalBox {
                                    // height: 80px;
                                    // width: 100%;
                                    XButton {
                                            font-size: 24px;
                                            text: "";
                                            height: 36px;
                                            width: 36px;
                                            icon: item.tranxType == TranxType.input ? @image-url("../assets/file_download.svg") : item.tranxType == TranxType.output ? @image-url("../assets/file_upload.svg") : @image-url("../assets/camera_alt.svg");
                                            show-icon: true;
                                            round: true;
                                            clicked => {
                                                if item.tranxType != TranxType.snapshot {
                                                    WalletAccounts.block-refreshing = true;
                                                    tranx-item = item;
                                                    show-tranx-block = true;
                                                }
                                            }
                                        }

                                        VerticalLayout {
                                            width: 100px;
                                            SText {
                                                text: item.tranxType == TranxType.input ? i18n.received : item.tranxType == TranxType.output ? i18n.sent : i18n.snapshot;
                                                font-size: 15px;
                                                font-weight: 700;
                                            }

                                            Rectangle {
                                                height: 5px;
                                            }

                                            SText {
                                                text: item.time;
                                                font-size: 15px;
                                                color: ROOT_GLOBAL.bottomNavColor;
                                            }
                                        }

                                        Rectangle { }

                                        SText {
                                            text: item.amount + " XDAG  ";
                                            overflow: clip;
                                            wrap: word-wrap;
                                            font-size: 16px;
                                            font-weight: 700;
                                            color: item.tranxType == TranxType.input ? ROOT_GLOBAL.greenColor : item.tranxType == TranxType.output ? ROOT_GLOBAL.textColorGray : ROOT_GLOBAL.mainColor54;
                                        }
                                    }
                                    Rectangle {
                                        height: 5px;
                                    }

                                    SDivider {
                                        width: 95%;
                                    }

                                    Rectangle {
                                        height: 8px;
                                    }
                                }
                                Rectangle { }
                            }
                        }
                    }
                }
            }
        }

        animate y {
            duration: 450ms;
            easing: ease;
        }
    }

    HorizontalLayout {
        x: 0;
        y: 0;
        width: 100%;
        height: ROOT-GLOBAL.window-height;
        VerticalLayout {
            width: 18%;
            height: 100%;
            padding-top: 40px;
            padding-bottom: 10px;
            padding-left: 8px;
            padding-right: 8px;
            Rectangle {
                Image {
                    width: 70px;
                    source: @image-url("../assets/logo.png");
                }
            }

            Rectangle {
                height: 2%;
            }

            SText {
                font-weight: 800;
                font-size: 15px;
                horizontal-alignment: center;
                text: @tr("XDAG Plus");
            }

            Rectangle { }

            walletBtn := Button {
                primary: true;
                colorize-icon: true;
                icon: @image-url("../assets/account_balance_wallet.svg");
                text: i18n.wallet;
                clicked => {
                    walletBtn.primary = true;
                    contactsBtn.primary = false;
                    settingsBtn.primary = false;
                    contacts-view.y = parent.height;
                    settings-view.y = parent.height;
                    account-view.y = header-bar.height;
                }
            }

            Rectangle {
                height: 2%;
            }

            contactsBtn := Button {
                colorize-icon: true;
                icon: @image-url("../assets/person.svg");
                text: i18n.contacts;
                clicked => {
                    contactsBtn.primary = true;
                    walletBtn.primary = false;
                    settingsBtn.primary = false;
                    contacts-view.y = 0;
                    settings-view.y = parent.height;
                    account-view.y = -1 * parent.height;
                }
            }

            Rectangle {
                height: 2%;
            }

            settingsBtn := Button {
                colorize-icon: true;
                icon: @image-url("../assets/settings_applications.svg");
                text: i18n.setting;
                clicked => {
                    settingsBtn.primary = true;
                    walletBtn.primary = false;
                    contactsBtn.primary = false;
                    contacts-view.y = -1 * parent.height;
                    settings-view.y = 0;
                    account-view.y = -1 * parent.height;
                }
            }

            Rectangle { }

            SText {
                color: ROOT-GLOBAL.versionColor;
                font-size: 14px;
                horizontal-alignment: center;
                text: ROOT-GLOBAL.version;
            }
        }

        // VerticalLayout {
        //     // height: 100%;
        //     width: parent.width * 85%;
            header-bar := HorizontalLayout {
            width: parent.width * 82%;
            padding-top: 3px;
            padding-right: 10px;
            height: 38px;
            alignment: end;
            spacing: 8px;
            Rectangle {
                height: 32px;
                width: 65px;
                netType := SText {
                    color: WalletAccounts.is-test ? ROOT_GLOBAL.redColor : ROOT_GLOBAL.greenColor;
                    vertical-alignment: bottom;
                    font-size: 16px;
                    font-weight: 800;
                    text: WalletAccounts.is-test ? @tr("TestNet") : @tr("MainNet");
                }

                TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        show-network = true;
                    }
                }
            }

            XButton {
                font-size: 20px;
                text: "";
                height: parent.height * 85%;
                width: parent.height * 85%;
                icon: @image-url("../assets/lock.svg");
                show-icon: true;
                round: true;
                clicked => {
                    WalletAccounts.is-lock = true;
                    show-password-check = true;
                }
            }

            XButton {
                font-size: 20px;
                text: "";
                height: parent.height * 85%;
                width: parent.height * 85%;
                icon: @image-url("../assets/refresh.svg");
                show-icon: true;
                round: true;
                clicked => {
                    WalletAccounts.fetching = true;
                    WalletAccounts.is-tranx-empty = true;
                    WalletAccounts.fetch-history(WalletAccounts.is-test, UiWallets.ui-wallets[active-index].address);
                }
            }
        }
        // }

        Rectangle {
            width: 100%;
            height: ROOT-GLOBAL.window-height;
            background: ROOT-GLOBAL.bgColorMask2;
        }
    }

    Rectangle {
        width: 100%;
        height: 100%;
        if show-select-wallet: Rectangle {
            width: 100%;
            height: 100%;
            x: 0;
            background: ROOT_GLOBAL.bgColorMask-transparent;
            animate background {
                duration: 450ms;
                easing: ease;
            }
        }
        if show-select-wallet: Rectangle {
            width: root.width * 50%;
            height: 100%;
            x: 0;
            TouchArea {
                clicked => {
                    root.show-select-wallet = false;
                    select-wallet.x = root.width;
                }
            }
        }
        select-wallet := Rectangle {
            width: root.width * 50%;
            height: 100%;
            x: root.width;
            background: ROOT_GLOBAL.bgColorMask2;
            VerticalLayout {
                padding-top: 8px;
                padding-bottom: 18px;
                HorizontalBox {
                    XButton {
                        font-size: 16px;
                        text: "";
                        height: 28px;
                        width: 28px;
                        icon: @image-url("../assets/close.svg");
                        show-icon: true;
                        round: true;
                        clicked => {
                            root.show-select-wallet = false;
                            select-wallet.x = root.width;
                        }
                    }

                    Rectangle {
                        SText {
                            horizontal-alignment: center;
                            min-width: 200px;
                            text: i18n.select_Wallet;
                            font-size: 24px;
                            font-weight: 800;
                        }
                    }
                }

                Rectangle {
                    height: 10px;
                }

                ScrollView {
                    width: 100%;
                    height: 74%;
                    VerticalLayout {
                        width: root.width * 47%;
                        alignment: start;
                        for wlt[idx] in UiWallets.ui-wallets: VerticalLayout {
                            padding: 8px;
                            Rectangle {
                                border-width: 1px;
                                border-color: idx == active-index ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
                                border-radius: 10px;
                                background: ROOT-GLOBAL.blockColor;
                                Rectangle {
                                    x: 0;
                                    y: 0;
                                    width: wlt-name.width + name-space.width;
                                    height: 100%;
                                    TouchArea {
                                        mouse-cursor: pointer;
                                        clicked => {
                                            if idx != active-index {
                                                active-index = idx;
                                                walletName.text = wlt.name;
                                                walletAddress.text = wlt.address;
                                                WalletAccounts.current-address = wlt.address;
                                                // walletValue.text = wlt.balance;
                                                WalletAccounts.fetching = true;
                                                WalletAccounts.is-tranx-empty = true;
                                                WalletAccounts.fetch-history(WalletAccounts.is-test, wlt.address);
                                                root.show-select-wallet = false;
                                                select-wallet.x = root.width;
                                            }
                                        }
                                    }
                                }

                                VerticalLayout {
                                    padding: 5px;
                                    alignment: start;
                                    HorizontalBox {
                                        wlt-name := SText {
                                            text: wlt.name;
                                            min-width: 250px;
                                            font-size: 24px;
                                            font-weight: 800;
                                        }

                                        name-space := Rectangle { }

                                        XButton {
                                            font-size: 20px;
                                            text: "";
                                            height: 36px;
                                            width: 36px;
                                            icon: @image-url("../assets/delete.svg");
                                            show-icon: true;
                                            colorized: ROOT-GLOBAL.redColor;
                                            round: true;
                                            clicked => {
                                                del-wallet.wallet-index = idx;
                                                del-wallet.visible = true;
                                            }
                                        }

                                        XButton {
                                            font-size: 20px;
                                            text: "";
                                            height: 36px;
                                            width: 36px;
                                            icon: @image-url("../assets/edit.svg");
                                            show-icon: true;
                                            colorized: darkorange;
                                            round: true;
                                            clicked => {
                                                rename-win.old-name = wlt.name;
                                                rename-win.new-name = wlt.name;
                                                rename-win.index = idx;
                                                rename-win.visible = true;
                                            }
                                        }

                                        XButton {
                                            font-size: 20px;
                                            text: "";
                                            height: 36px;
                                            width: 36px;
                                            icon: @image-url("../assets/content_copy.svg");
                                            show-icon: true;
                                            round: true;
                                            clicked => {
                                                clipboard.text = wlt.address;
                                                clipboard.select-all();
                                                clipboard.copy();
                                            }
                                        }

                                        // XButton {
                                        //     font-size: 20px;
                                        //     text: "";
                                        //     height: 36px;
                                        //     width: 36px;
                                        //     icon: idx == active-index ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                                        //     show-icon: true;
                                        //     round: true;
                                        //     clicked => {
                                        //         if idx != active-index {
                                        //             active-index = idx;
                                        //             walletName.text = wlt.name;
                                        //             walletAddress.text = wlt.address;
                                        //             WalletAccounts.current-address = wlt.address;
                                        //         // walletValue.text = wlt.balance;
                                        //         WalletAccounts.fetching = true;
                                        //             WalletAccounts.is-tranx-empty = true;
                                        //             WalletAccounts.fetch-history(WalletAccounts.is-test, wlt.address);
                                        //         }
                                        //     }
                                        // }
                                    }

                                    SText {
                                        text: wlt.address;
                                        font-size: 16px;
                                        font-weight: 500;
                                        color: idx == active-index ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.textColorGray;
                                    }

                                    Rectangle {
                                        height: 5px;
                                    }
                                }
                            }

                            Rectangle {
                                height: 2px;
                            }
                        }
                    }
                }

                Rectangle { }

                SDivider {
                    width: 90%;
                }

                VerticalBox {
                    padding: 15px;
                    Button {
                        height: 35px;
                        min-width: 100px;
                        primary: true;
                        text: i18n.createWallet;
                        clicked => {
                            show-create-win = true;
                        }
                    }

                    Button {
                        height: 35px;
                        min-width: 100px;
                        text: i18n.importWallet;
                        clicked => {
                            show-import-win = true;
                        }
                    }
                }
            }

            animate x {
                duration: 450ms;
                easing: ease;
            }
        }
    }

    contacts-view := Rectangle {
        height: parent.height;
        width: parent.width * 82%;
        x: parent.width * 18%;
        y: parent.height;
        background: ROOT_GLOBAL.bgColorMask2;
        border-radius: 8px;
        VerticalLayout {
            padding: 20px;
            alignment: start;
            HorizontalBox {
                Rectangle {
                    SText {
                        min-width: 200px;
                        text: i18n.contacts;
                        font-size: 32px;
                        font-weight: 800;
                    }
                }

                Rectangle { }

                Rectangle {
                    XButton {
                        font-size: 28px;
                        text: "";
                        height: 36px;
                        width: 36px;
                        icon: @image-url("../assets/add_circle_outline.svg");
                        show-icon: true;
                        round: true;
                        clicked => {
                            edit-contact-address = "";
                            edit-contact-name = "";
                            show-add-contact = true;
                        }
                    }
                }
            }

            Rectangle {
                height: 15px;
            }

            ScrollView {
                width: 100%;
                height: 85%;
                VerticalLayout {
                    padding: 10px;
                    alignment: start;
                    for address[idx] in WalletAccounts.favorite-model: VerticalLayout { // Display favorite addresses
                        Rectangle {
                            height: 5px;
                        }

                        HorizontalLayout {
                            SText {
                                min-width: 400px;
                                text: address.name;
                                font-size: 22px;
                                font-weight: 800;
                            }

                            Rectangle { }

                            if idx == 0:HorizontalLayout {
                                spacing: 5px;
                                Image {
                                    source: @image-url("../assets/star_rate.svg");
                                    colorize: ROOT_GLOBAL.yellowColor;
                                }

                                XButton {
                                    font-size: 20px;
                                    text: "";
                                    height: 36px;
                                    width: 36px;
                                    icon: @image-url("../assets/content_copy.svg");
                                    show-icon: true;
                                    round: true;
                                    clicked => {
                                        clipboard.text = address.address;
                                        clipboard.select-all();
                                        clipboard.copy();
                                    }
                                }
                            }
                            if idx > 0:HorizontalLayout {
                                spacing: 5px;
                                XButton {
                                    font-size: 20px;
                                    text: "";
                                    height: 36px;
                                    width: 36px;
                                    icon: @image-url("../assets/delete.svg");
                                    show-icon: true;
                                    colorized: ROOT-GLOBAL.redColor;
                                    round: true;
                                    clicked => {
                                        // WalletAccounts.delete-contact(idx);
                                        // WalletAccounts.set-config();
                                        del-contact.contact-index = idx;
                                        del-contact.visible = true;
                                    }
                                }

                                XButton {
                                    font-size: 20px;
                                    text: "";
                                    height: 36px;
                                    width: 36px;
                                    icon: @image-url("../assets/edit.svg");
                                    show-icon: true;
                                    colorized: darkorange;
                                    round: true;
                                    clicked => {
                                        edit-contact-index = idx;
                                        edit-contact-name = address.name;
                                        edit-contact-address = address.address;
                                        show-add-contact = true;
                                    }
                                }

                                XButton {
                                    font-size: 20px;
                                    text: "";
                                    height: 36px;
                                    width: 36px;
                                    icon: @image-url("../assets/content_copy.svg");
                                    show-icon: true;
                                    round: true;
                                    clicked => {
                                        clipboard.text = address.address;
                                        clipboard.select-all();
                                        clipboard.copy();
                                    }
                                }
                            }
                        }

                        Rectangle {
                            height: 5px;
                        }

                        SText {
                            text: address.address;
                            font-size: 18px;
                            font-weight: 600;
                            color: ROOT-GLOBAL.textColorGray;
                        }

                        Rectangle {
                            height: 10px;
                        }

                        SDivider {
                            width: 100%;
                        }
                    }
                }
            }
        }

        animate y {
            duration: 450ms;
            easing: ease;
        }
    }

    settings-view := Rectangle {
        height: parent.height;
        width: parent.width * 82%;
        x: parent.width * 18%;
        y: parent.height;
        background: ROOT_GLOBAL.bgColorMask2;
        border-radius: 8px;
        VerticalLayout {
            padding: 20px;
            // alignment: start;
            SText {
                min-width: 300px;
                text: i18n.setting;
                font-size: 32px;
                font-weight: 800;
            }

            Rectangle {
                height: parent.height * 5%;
            }

            HorizontalLayout {
                alignment: center;
                // Rectangle {
                //     height: root.height * 60%;
                //     width: root.width * 40%;
                GridLayout {
                    height: root.height * 60%;
                    width: root.width * 40%;
                    spacing: 20px;
                    Rectangle {
                        row: 0;
                        col: 0;
                        background: t1.pressed ? ROOT_GLOBAL.blockColor : t1.has-hover ? ROOT_GLOBAL.transactionColor : ROOT_GLOBAL.blockColor;
                        border-radius: 8px;
                        VerticalLayout {
                            alignment: center;
                            Rectangle {
                                height: 30px;
                            }

                            Image {
                                source: @image-url("../assets/language.svg");
                                colorize: ROOT_GLOBAL.textColorGray;
                            }

                            Rectangle {
                                height: 30px;
                            }

                            SText {
                                min-width: 100px;
                                text: i18n.sele-lang-name;
                                font-size: 18px;
                                horizontal-alignment: center;
                            }

                            Rectangle {
                                height: 30px;
                            }
                        }

                        t1 := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                show-language = true;
                            }
                        }
                    }

                    Rectangle {
                        row: 0;
                        col: 1;
                        background: t2.pressed ? ROOT_GLOBAL.blockColor : t2.has-hover ? ROOT_GLOBAL.transactionColor : ROOT_GLOBAL.blockColor;
                        border-radius: 8px;
                        VerticalLayout {
                            alignment: center;
                            Rectangle {
                                height: 30px;
                            }

                            Image {
                                source: @image-url("../assets/wifi.svg");
                                colorize: ROOT_GLOBAL.textColorGray;
                            }

                            Rectangle {
                                height: 30px;
                            }

                            SText {
                                min-width: 100px;
                                text: WalletAccounts.is-test ? "TestNet" : "MainNet";
                                font-size: 18px;
                                horizontal-alignment: center;
                            }

                            Rectangle {
                                height: 30px;
                            }
                        }

                        t2 := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                show-network = true;
                            }
                        }
                    }

                    Rectangle {
                        row: 1;
                        col: 0;
                        background: t3.pressed ? ROOT_GLOBAL.blockColor : t3.has-hover ? ROOT_GLOBAL.transactionColor : ROOT_GLOBAL.blockColor;
                        border-radius: 8px;
                        VerticalLayout {
                            alignment: center;
                            Rectangle {
                                height: 30px;
                            }

                            Image {
                                source: @image-url("../assets/security.svg");
                                colorize: ROOT_GLOBAL.textColorGray;
                            }

                            Rectangle {
                                height: 30px;
                            }

                            SText {
                                min-width: 100px;
                                text: "Security";
                                font-size: 18px;
                                horizontal-alignment: center;
                            }

                            Rectangle {
                                height: 30px;
                            }
                        }

                        t3 := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                WalletAccounts.is-change-pswd = true;
                                show-password-check = true;
                            }
                        }
                    }

                    Rectangle {
                        row: 1;
                        col: 1;
                        background: t4.pressed ? ROOT_GLOBAL.blockColor : t4.has-hover ? ROOT_GLOBAL.transactionColor : ROOT_GLOBAL.blockColor;
                        border-radius: 8px;
                        VerticalLayout {
                            alignment: center;
                            Rectangle {
                                height: 30px;
                            }

                            Image {
                                source: @image-url("../assets/slint.svg");
                                colorize: ROOT_GLOBAL.textColorGray;
                            }

                            Rectangle {
                                height: 30px;
                            }

                            SText {
                                min-width: 100px;
                                text: "Slint";
                                font-size: 18px;
                                horizontal-alignment: center;
                            }

                            Rectangle {
                                height: 30px;
                            }
                        }

                        t4 := TouchArea {
                            mouse-cursor: pointer;
                            clicked => {
                                about-slint.visible = true;
                            }
                        }
                    }
                }
                // }
            }

            Rectangle { }

            HorizontalLayout {
                alignment: center;
                SText {
                    min-width: 300px;
                    text: i18n.about_us;
                    font-size: 14px;
                    horizontal-alignment: center;
                }
            }

            Rectangle {
                height: 20px;
            }

            HorizontalLayout {
                alignment: center;
                spacing: 35px;
                XButton {
                    font-size: 20px;
                    text: "";
                    height: 36px;
                    width: 36px;
                    icon: @image-url("../assets/telegram.svg");
                    show-icon: true;
                    round: true;
                    clicked => {
                        WalletAccounts.open-link(ROOT-GLOBAL.telegram);
                    }
                }

                XButton {
                    font-size: 20px;
                    text: "";
                    height: 36px;
                    width: 36px;
                    icon: @image-url("../assets/discord.svg");
                    show-icon: true;
                    round: true;
                    clicked => {
                        WalletAccounts.open-link(ROOT-GLOBAL.discord);
                    }
                }

                XButton {
                    font-size: 20px;
                    text: "";
                    height: 36px;
                    width: 36px;
                    icon: @image-url("../assets/twitter.svg");
                    show-icon: true;
                    round: true;
                    clicked => {
                        WalletAccounts.open-link(ROOT-GLOBAL.twitter);
                    }
                }

                XButton {
                    font-size: 20px;
                    text: "";
                    height: 36px;
                    width: 36px;
                    icon: @image-url("../assets/home.svg");
                    show-icon: true;
                    round: true;
                    clicked => {
                        WalletAccounts.open-link(ROOT-GLOBAL.home-site);
                    }
                }
            }
        }

        animate y {
            duration: 450ms;
            easing: ease;
        }
    }

    if show-language: Rectangle {
        width: 100%;
        height: 100%;
        background: ROOT-GLOBAL.bgColorMask-transparent;
        LanguageWin {
            z: 111;
            lang-name: Language.name;
            width: root.width * 50%;
            height: root.height * 55%;
            close => {
                show-language = false;
            }
            action => {
                show-language = false;
                WalletAccounts.set-config();
            }
        }

        TouchArea { }
    }
    if show-network: Rectangle {
        width: 100%;
        height: 100%;
        background: ROOT-GLOBAL.bgColorMask-transparent;
        NetworkWin {
            z: 111;
            lang-name: Language.name;
            width: root.width * 40%;
            height: root.height * 35%;
            close => {
                show-network = false;
            }
            action(is-test) => {
                if WalletAccounts.is-test != is-test {
                    WalletAccounts.fetching = true;
                    WalletAccounts.is-tranx-empty = true;
                    WalletAccounts.fetch-history(is-test, UiWallets.ui-wallets[active-index].address);
                }
                WalletAccounts.is-test = is-test;
                show-network = false;
                WalletAccounts.set-config();
            }
        }

        TouchArea { }
    }
    if show-create-win:  Rectangle {
        width: 100%;
        height: 100%;
        background: ROOT-GLOBAL.bgColorMask-transparent;
        CreateWallet {
            lang-name: Language.name;
            z: 111;
            width: root.width * 55%;
            height: root.height * 50%;
            close => {
                show-create-win = false;
                mnemonic-words = "";
            }
            action(name, pswd) => {
                WalletAccounts.create-wallet(name, WalletAccounts.current-password, mnemonic-words);
            }
        }

        TouchArea { }
    }
    if show-import-win:  Rectangle {
        width: 100%;
        height: 100%;
        background: ROOT-GLOBAL.bgColorMask-transparent;
        ImportWallet {
            lang-name: Language.name;
            z: 111;
            width: root.width * 55%;
            height: root.height * 50%;
            placehold: i18n.mnemonic_hint_1;
            btn-text: i18n.continueText;
            close => {
                show-import-win = false;
            }
            action(words) => {
                mnemonic-words = words;
                show-create-win = true;
            }
        }

        TouchArea { }
    }
    if show-add-contact:  Rectangle {
        width: 100%;
        height: 100%;
        background: ROOT-GLOBAL.bgColorMask-transparent;
        Contacts {
            lang-name <=> Language.name;
            z: 111;
            width: root.width * 55%;
            height: root.height * 52%;
            is-edit: edit-contact-name != "";
            contact-name: edit-contact-name;
            contatc-address: edit-contact-address;
            close => {
                show-add-contact = false;
            }
            action(name, address) => {
                if edit-contact-name == "" {
                    WalletAccounts.add-contact(name, address);
                } else {
                    WalletAccounts.favorite-model[edit-contact-index] = {
                        name: name,
                        address: address,
                    };
                }
                WalletAccounts.set-config();
                show-add-contact = false;
            }
        }

        TouchArea { }
    }
    if show-qr-code: Qrcode {
        close => {
            show-qr-code = false;
        }
    }
    if show-mnemonic-words: MnemonicWin {
        lang-name: Language.name;
        copy-mnemonic => {
            clipboard.text = UiWallets.ui-wallets[active-index].mnemonic;
            clipboard.select-all();
            clipboard.copy();
        }
        close => {
            show-mnemonic-words = false;
        }
    }
    if show-tranx-block: Transaction {
        lang-name: Language.name;
        item: tranx-item;
        copy-to(str) => {
            clipboard.text = str;
            clipboard.select-all();
            clipboard.copy();
        }
        close => {
            show-tranx-block = false;
        }
    }
    if show-send-win: SendWin {
        width: 100%;
        height: 100%;
        lang-name: Language.name;
        receiver: toAddress.text;
        sender: walletAddress.text;
        amount: Amount.text;
        remark: Remark.text;
        close => {
            show-send-win = false;
            if WalletAccounts.sent {
                toAddress.text = "";
                Amount.text = "";
                Remark.text = "";
            }
        }
        send-action() => {
            show-password-check = true;
        }
    }
    if show-password-check: PasswordView {
        go-back => {
            show-password-check = false;
            show-send-win = false;
            WalletAccounts.is-change-pswd = false;
        }
        check_password(ps) => {
            if WalletAccounts.is-lock {
                // lock screen
                WalletAccounts.is-lock = ps != WalletAccounts.current-password;
                show-password-check = ps != WalletAccounts.current-password;
            } else if WalletAccounts.is-change-pswd {
                show-password-check = ps != WalletAccounts.current-password;
                if !show-password-check {
                    security-win.win-title = i18n.desktop_change_password;
                    security-win.visible = true;
                    security-win.reinput();
                    security-win.show-btn();
                }
            } else {
                show-password-check = ps != WalletAccounts.current-password;
                if ps == WalletAccounts.current-password && !show-send-win {
                    show-mnemonic-words = true;
                }
                if ps == WalletAccounts.current-password && show-send-win {
                    WalletAccounts.sending = true;
                    WalletAccounts.sent = false;
                    send-timer.running = true;
                    // WalletAccounts.send-xdag(WalletAccounts.is-test,UiWallets.ui-wallets[active-index].mnemonic,
                    // walletAddress.text,toAddress.text, Amount.text, Remark.text);
                }
            }
            return ps == WalletAccounts.current-password;
        }
    }
    send-timer := Timer {
        interval: 150ms;
        running: false;
        triggered => {
            WalletAccounts.send-xdag(WalletAccounts.is-test,UiWallets.ui-wallets[active-index].mnemonic,
                walletAddress.text,toAddress.text, Amount.text, Remark.text, WalletAccounts.extra-fee);
            self.running = false;
        }
    }

    del-contact := DelContact {
        visible: false;
        lang-name: Language.name;
        close => {
            self.visible = false;
        }
    }

    del-wallet := DelWallet {
        visible: false;
        lang-name: Language.name;
        close => {
            self.visible = false;
        }
        action(index) => {
            WalletAccounts.delete-wallet(index);
            active-index = 0;
            walletName.text = UiWallets.ui-wallets[active-index].name;
            walletAddress.text = UiWallets.ui-wallets[active-index].address;
            WalletAccounts.current-address = UiWallets.ui-wallets[active-index].address;
            WalletAccounts.fetching = true;
            WalletAccounts.is-tranx-empty = true;
            WalletAccounts.fetch-history(WalletAccounts.is-test, UiWallets.ui-wallets[active-index].address);
            self.visible = false;
            root.show-select-wallet = false;
            select-wallet.x = root.width;
        }
    }

    err-win := ErrorWin {
        visible: WalletAccounts.err-visible;
        lang-name: Language.name;
        message: WalletAccounts.err-message;
        close => {
            WalletAccounts.err-visible = false;
            // self.visible = false;
        }
    }

    rename-win := RenameWallet {
        visible: false;
        lang-name: Language.name;
        close => {
            self.visible = false;
        }
        action(index, name) => {
            WalletAccounts.rename-wallet(self.old-name,name);
            UiWallets.ui-wallets[index].name = name;
            if index == active-index {
                walletName.text = name;
            }
        }
    }

    security-win := SecurityWin {
        visible: false;
        close => {
            self.visible = false;
            WalletAccounts.is-change-pswd = false;
        }
        check_password(pswd) => {
            self.visible = false;
            WalletAccounts.is-change-pswd = false;
            WalletAccounts.change-password(WalletAccounts.current-password,pswd);
        }
    }

    about-slint := About {
        visible: false;
    }

    clipboard := LineEdit {
        visible: false;
    }
}
