import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { Themes } from "../modules/surrealism-ui/use/index.slint";
import { Button, HorizontalBox, LineEdit, CheckBox } from "std-widgets.slint";
import {I18n} from "../i18n.slint";
import {ROOT_GLOBAL, WalletAccounts, UiWallets} from "../global.slint";
import { XlineEdit } from "xline-edit.slint";

export component CreateWallet inherits Rectangle {
    in-out property <string> lang-name;
    in-out property <string> wallet-name <=> name.text;
    callback close();
    callback action(string, string);
    private property <bool> confirm:false;
    border-color: ROOT-GLOBAL.borderColor;
    border-width: 1px;
    border-radius: 10px;
    background: ROOT-GLOBAL.bgColor;
    i18n := I18n {
        lang <=> lang-name;
    }

    SText {
        x: 8px;
        y: 10px;
        font-size: 20px;
        font-weight: 900;
        width: parent.width * 50%;
        text: i18n.createWallet;
    }

    top-bar := HorizontalBox {
        y: 0;
        width: 100%;
        height: 40px;
        alignment: end;
        XButton {
            font-size: 16px;
            text: "";
            height: parent.height * 70%;
            width: parent.height * 70%;
            icon: @image-url("../assets/close.svg");
            show-icon: true;
            round: true;
            clicked => {
                close();
            }
        }
    }

    SDivider {
        y: 50px;
        width: 100%;
    }

    VerticalLayout {
        width: 90%;
        alignment: center;
        Rectangle {
            height: 10%;
        }

        SText {
            font-size: 18px;
            font-weight: 800;
            text: i18n.walletName;
        }

        Rectangle {
            height: 3%;
        }

        name := XlineEdit {
            lang-name: lang-name;
            font-size: 16px;
            height: 40px;
            placeholder-text: i18n.walletName;
        }

        Rectangle {
            height: 5%;
        }

        // SText {
        //     text: i18n.create_password;
        // }

        // Rectangle {
        //     height: 2%;
        // }

        // pass := LineEdit {
        //     input-type: password;
        //     placeholder-text: i18n.create_password;
        // }

        // Rectangle {
        //     height: 5%;
        // }

        // SText {
        //     text: i18n.repeat_password;
        // }

        // Rectangle {
        //     height: 2%;
        // }

        // pass2 := LineEdit {
        //     input-type: password;
        //     placeholder-text: i18n.repeat_password;
        // }

        // Rectangle {
        //     height: 5%;
        // }

        HorizontalBox {
            CheckBox {
                toggled => {
                    confirm = self.checked;
                }
            }

            SText {
                text: i18n.createWalletTips;
            }
        }

        Rectangle {
            height: 8%;
        }

        HorizontalBox {
            alignment: end;
            Button {
                primary: true;
                min-width: 100px;
                text: i18n.continueText;
                enabled: confirm && name.text != "";
                clicked => {
                    if UiWallets.ui-wallets.length > 0 {
                        action(name.text,UiWallets.ui-wallets[0].password);
                    } else {
                        action(name.text,""); // Assuming the password is empty if no wallets exist

                    }
                    close();
                }
            }
        }
    }

    Rectangle { }
}
