import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import {  HorizontalBox, Button } from "std-widgets.slint";
import {I18n,Language} from "../i18n.slint";
import {ROOT_GLOBAL,WalletAccounts} from "../global.slint";

export component ErrorWin inherits Rectangle {
    in-out property <string> lang-name;
    in-out property <string> title;
    in-out property <string> message;
    in-out property <int> wallet-index;
    callback close();
    callback action();
    i18n := I18n {
        lang <=> lang-name;
    }

    z: 1000;
    width: 100%;
    height: 100%;
    background: ROOT-GLOBAL.bgColorMask-transparent;
    Rectangle {
        z: 2000;
        width: root.width * 50%;
        height: root.height * 40%;
        border-color: ROOT-GLOBAL.redColor;
        border-width: 1px;
        background: ROOT-GLOBAL.bgColor;
        border-radius: 10px;
        SText {
            x: 8px;
            y: 10px;
            font-size: 20px;
            font-weight: 900;
        // width: parent.width * 50%;
        min-width: 300px;
            horizontal-alignment: left;
            text: i18n.error;
        }

        top-bar := HorizontalBox {
            y: 0;
        // width: 100%;
        height: 40px;
            alignment: end;
            XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 70%;
                width: parent.height * 70%;
                icon: @image-url("../assets/close.svg");
                show-icon: true;
                round: true;
                clicked => {
                    close();
                }
            }
        }

        SDivider {
            y: 50px;
            width: 100%;
        }

        VerticalLayout {
            // padding-top: 10px;
            padding-left: 10px;
            padding-right: 10px;
            alignment: start;
            y: 60px;
            spacing: 10px;
            Rectangle {
                width: 100%;
                height: 50%;
                SText {
                    width: parent.width * 90%;
                    horizontal-alignment: left;
                    vertical-alignment: top;
                    wrap: word-wrap;
                    overflow: clip;
                    // min-width: 400px;
                    min-height: 60px;
                    font-weight: 600;
                    text: WalletAccounts.err-message;
                    font-size: 18px;
                }
            }

            HorizontalLayout {
                padding-top: 5px;
                padding-right: 8px;
                alignment: end;
                Button {
                    min-width: 100px;
                    text: i18n.cancel;
                    clicked => {
                        close()
                    }
                }

                Rectangle {
                    width: 15px;
                }

                Button {
                    min-width: 100px;
                    primary: true;
                    text: i18n.continueText;
                    clicked => {
                        close();
                    }
                }
            }
        }
    }

    TouchArea {
        clicked => {
        }
    }
}
