import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import {  HorizontalBox } from "std-widgets.slint";
import {I18n,Language} from "../i18n.slint";
import {ROOT_GLOBAL} from "../global.slint";


export component LanguageWin inherits Rectangle {
    in-out property <string> lang-name;
    callback close();
    callback action();
    i18n := I18n {
        lang <=> lang-name;
    }

    z: 111;
    border-color: ROOT-GLOBAL.borderColor;
    border-width: 1px;
    background: ROOT-GLOBAL.bgColor;
    border-radius: 10px;
    SText {
        x: 8px;
        y: 10px;
        font-size: 20px;
        font-weight: 900;
        width: parent.width * 50%;
        text: i18n.select_language;
    }

    top-bar := HorizontalBox {
        y: 0;
        width: 100%;
        height: 40px;
        alignment: end;
        XButton {
            font-size: 16px;
            text: "";
            height: parent.height * 70%;
            width: parent.height * 70%;
            icon: @image-url("../assets/close.svg");
            show-icon: true;
            round: true;
            clicked => {
                close();
            }
        }
    }

    SDivider {
        y: 50px;
        width: 100%;
    }

    GridLayout {
        padding: 10px;
        y: 60px;
        spacing: 20px;
        Rectangle {
            height: 50px;
            border-color: Language.name == "en_US" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "en_US" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 0;
            col: 0;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "English";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "en_US" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "en_US";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "zh_CN" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "zh_CN" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 0;
            col: 1;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "简体中文";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "zh_CN" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "zh_CN";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "fr_FR" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "fr_FR" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 1;
            col: 0;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "Français";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "fr_FR" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "fr_FR";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "ru_RU" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "ru_RU" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 1;
            col: 1;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "Русский";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "ru_RU" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "ru_RU";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "es_ES" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "es_ES" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 2;
            col: 0;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "Español";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "es_ES" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "es_ES";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "it_IT" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "it_IT" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 2;
            col: 1;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "Italiano";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "it_IT" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "it_IT";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "de_DE" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "de_DE" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 3;
            col: 0;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "Deutsch";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "de_DE" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "de_DE";
                    action();
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: Language.name == "ja_JP" ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: Language.name == "ja_JP" ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            row: 3;
            col: 1;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "日本語";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: Language.name == "ja_JP" ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    Language.name = "ja_JP";
                    action();
                }
            }
        }
    }
}
