import {ROOT_GLOBAL, WalletAccounts, UiWallets, TranxItem,TranxType} from "../global.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { SText } from "../modules/surrealism-ui/index.slint";
import {I18n, Language} from "../i18n.slint";
import { Button, CheckBox, SpinBox, Slider } from "std-widgets.slint";


export component SendWin inherits Rectangle {
    in-out property <string> receiver;
    in-out property <string> sender;
    in-out property <string> amount;
    in-out property <string> amount-p: self.amount + ((self.amount + ".00").is-float() ? ".00" : "") + "  XDAG";
    in-out property <string> amount-n: "- " + amount-p;
    in-out property <string> remark;
    in-out property <string> lang-name;
    property <bool> enable-fee: false;
    property <float> fee-value: 0.0;
    property <int> fee-int: 0;
    i18n := I18n {
        lang <=> lang-name;
    }

    callback close();
    callback send-action();

    background: ROOT-GLOBAL.bgColorMask-transparent;
    Rectangle {
        z: 111;
        width: root.width * 75%;
        height: root.height * 75%;
        background: ROOT-GLOBAL.bgColor;
        border-color: ROOT-GLOBAL.borderColor;
        border-width: 1px;
        border-radius: 10px;
        HorizontalLayout {
            padding: 8px;
            y: 0;
            width: 100%;
            height: 60px;
            SText {
                min-width: 100px;
                text: WalletAccounts.sent ? i18n.sent : i18n.send;
                font-size: 20px;
                font-weight: 900;
            }

            Rectangle { }

            Rectangle {
                width: 15px;
            }

            if !WalletAccounts.sending:XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 50%;
                width: parent.height * 50%;
                icon: @image-url("../assets/close.svg");
                show-icon: true;
                round: true;
                clicked => {
                    close();
                }
            }
        }

        VerticalLayout {
            padding: 10px;
            alignment: start;
            y: 60px;
            spacing: 20px;
            VerticalLayout {
                alignment: start;
                spacing: 10px;
                SText {
                    horizontal-alignment: center;
                    min-width: 400px;
                    text: WalletAccounts.sent ? amount-n : amount-p;
                    font-size: 30px;
                    font-weight: 600;
                    color: WalletAccounts.sent ? ROOT_GLOBAL.textColorGray : ROOT_GLOBAL.greenColor;
                }

                if WalletAccounts.sent:SText {
                    horizontal-alignment: center;
                    min-width: 400px;
                    text: i18n.state + ": " + WalletAccounts.current-block-info.state;
                    font-size: 18px;
                    font-weight: 600;
                    color: WalletAccounts.current-block-info.state == "Accepted" ? ROOT_GLOBAL.greenColor : ROOT_GLOBAL.redColor;
                }
                if !WalletAccounts.sent:Rectangle {
                    height: 20px;
                }
            }

            if WalletAccounts.sending:Rectangle {
                Image {
                    colorize: ROOT_GLOBAL.bottomNavColor;
                    width: 150px;
                    source: @image-url("../assets/spinner.svg");
                    rotation-angle: !WalletAccounts.sending ? 0deg : 240deg * animation-tick() / 1s;
                    animate rotation-angle {
                        easing: ease-in-out;
                        iteration-count: -1;
                    }
                }
            }
            if !WalletAccounts.sending:VerticalLayout {
                alignment: start;
                spacing: 5px;
                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: WalletAccounts.sent ? i18n.receiver : i18n.network;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.sent ? receiver : WalletAccounts.is-test ? @tr("TestNet") : @tr("MainNet");
                            font-size: 16px;
                            font-weight: 600;
                            color: WalletAccounts.sent ? Colors.whitesmoke : WalletAccounts.is-test ? ROOT_GLOBAL.redColor : ROOT_GLOBAL.greenColor;
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: WalletAccounts.sent ? "hash" : i18n.receiver;
                            font-size: 16px;
                        }

                        Rectangle { }

                        wlt-address := SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.sent ? WalletAccounts.current-block-info.hash : receiver;
                            font-size: WalletAccounts.sent ? 14px : 16px;
                            font-weight: 600;
                            color: receiver == sender ? ROOT_GLOBAL.redColor : Colors.whitesmoke;
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: WalletAccounts.sent ? i18n.block_address : i18n.sender;
                            font-size: 16px;
                        }

                        Rectangle { }

                        hash := SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.sent ? WalletAccounts.current-block-info.address : sender;
                            font-size: 16px;
                            font-weight: 600;
                            color: receiver == sender ? ROOT_GLOBAL.redColor : Colors.whitesmoke;
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: i18n.fee;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: "0.10 XDAG";
                            font-size: 16px;
                            font-weight: 600;
                            color: Colors.whitesmoke;
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: i18n.remark;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: remark;
                            font-size: 16px;
                            font-weight: 600;
                            color: remark.character-count > 32 ? ROOT_GLOBAL.redColor : Colors.whitesmoke;
                        }
                    }
                }
                Rectangle {
                  border-width: 1px;
                  background: ROOT_GLOBAL.blockColor;
                  border-radius: 8px;
                  HorizontalLayout {
                    visible: !WalletAccounts.sent;
                    padding: 4px;
                    check:= CheckBox {

                      min-width: 24px;
                      text: "";
                      checked: enable-fee;
                      changed checked => {
                        enable-fee = check.checked;
                        if !check.checked {
                          fee.value = 0;
                          fee-value = 0;
                          fee-int = 0;
                        }
                      }
                    }
                    Rectangle {
                      SText {
                          min-width: 190px;
                          text: "Express Fee: "+ fee-value + " XDAG";
                          font-size: 16px;
                      }
                      TouchArea {
                        clicked => {
                          if check.checked {
                            check.checked = false;
                          }else{
                            check.checked = true;
                          }
                          enable-fee = check.checked;
                        }
                      }
                    }

                    // fee := SpinBox {
                    //   max-width: 160px;
                    //   minimum: 0;
                    //   maximum: 1000;
                    //   value: 0;
                    //   step-size: 1;
                    //   enabled: enable-fee;
                    //   edited(value) => {
                    //     fee-value = value;
                    //   }
                    // }
                    fee := Slider {
                      min-width: 250px;
                      max-width: 250px;
                      minimum: 0;
                      maximum: 1000;
                      value: 0;
                      step: 1;
                      enabled: enable-fee;
                      changed(value) => {
                        fee-int = value;
                        fee-value = fee-int ;
                        fee-value = fee-value/10
                      }
                    }
                    Rectangle {}
                    SText {
                      horizontal-alignment: right;
                      min-width: 100px;
                      text: "Average Express Fee  :  ";
                      font-size: 16px;
                      font-weight: 600;
                      color: enable-fee? Colors.whitesmoke:ROOT_GLOBAL.blockColor;
                    }
                    SText {
                      horizontal-alignment: right;
                      text: WalletAccounts.average-express-fee;
                      font-size: 16px;
                      font-weight: 600;
                      color: enable-fee? Colors.whitesmoke:ROOT_GLOBAL.blockColor;
                    }
                  }
                  HorizontalLayout {
                    visible: WalletAccounts.sent;
                    padding: 8px;
                    SText {
                        min-width: 100px;
                        text: "Express Fee";
                        font-size: 16px;
                    }

                    Rectangle { }

                    SText {
                        horizontal-alignment: right;
                        min-width: 100px;
                        text: WalletAccounts.express-fee.to-fixed(2)+" XDAG";
                        font-size: 16px;
                        font-weight: 600;
                        color: Colors.whitesmoke;
                    }
                  }
                }
            }
            if !WalletAccounts.sending:HorizontalLayout {
                padding-top: 15px;
                padding-right: 20px;
                alignment: end;
                Button {
                    min-width: 100px;
                    primary: true;
                    text: WalletAccounts.sent ? i18n.view_in_explorer : i18n.send;
                    clicked => {
                        if self.text == i18n.view_in_explorer {
                            WalletAccounts.open-in-browser(WalletAccounts.is-test,WalletAccounts.current-block-info.address);
                        } else {
                            if remark.character-count <= 32 && receiver != sender && !receiver.is-empty {
                                WalletAccounts.express-fee = fee-value;
                                send-action();
                            }
                        }
                    }
                }
            }
        }
    }

    TouchArea {
        clicked => {
        }
    }
}
