import {ROOT_GLOBAL, WalletAccounts, UiWallets, TranxItem,TranxType} from "../global.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { SText } from "../modules/surrealism-ui/index.slint";
import {I18n, Language} from "../i18n.slint";
import { Button } from "std-widgets.slint";


export component Transaction inherits Rectangle {
    in-out property <TranxItem> item;
    in-out property <string> lang-name;
    in-out property <string> snd-rec-on:item.tranxType == TranxType.input ? i18n.receive_on : i18n.send_on;
    i18n := I18n {
        lang <=> lang-name;
    }

    init => {
        WalletAccounts.get-tranx-block(WalletAccounts.is-test,item.address,item.tranxType);
    }
    callback close();
    callback copy-to(string);
    width: 100%;
    height: 100%;
    background: ROOT-GLOBAL.bgColorMask-transparent;
    Rectangle {
        z: 111;
        width: root.width * 75%;
        height: root.height * 70%;
        background: ROOT-GLOBAL.bgColor;
        border-color: ROOT-GLOBAL.borderColor;
        border-width: 1px;
        border-radius: 10px;
        HorizontalLayout {
            padding: 8px;
            y: 0;
            width: 100%;
            height: 60px;
            SText {
                min-width: 100px;
                text: item.tranxType == TranxType.input ? i18n.received : i18n.sent;
                font-size: 20px;
                font-weight: 900;
            }

            Rectangle { }

            XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 50%;
                width: parent.height * 50%;
                icon: @image-url("../assets/refresh.svg");
                show-icon: true;
                round: true;
                clicked => {
                    if !WalletAccounts.block-refreshing {
                        WalletAccounts.block-refreshed = false;
                        WalletAccounts.block-refreshing = true;
                        WalletAccounts.get-tranx-block(WalletAccounts.is-test,item.address,item.tranxType);
                    }
                }
            }

            Rectangle {
                width: 15px;
            }

            XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 50%;
                width: parent.height * 50%;
                icon: @image-url("../assets/close.svg");
                show-icon: true;
                round: true;
                clicked => {
                    close();
                }
            }
        }

        if WalletAccounts.block-refreshing || !WalletAccounts.block-refreshed:Rectangle {
            Image {
                colorize: ROOT_GLOBAL.bottomNavColor;
                width: 150px;
                source: @image-url("../assets/spinner.svg");
                rotation-angle: !WalletAccounts.block-refreshing ? 0deg : 240deg * animation-tick() / 1s;
                animate rotation-angle {
                    easing: ease-in-out;
                    iteration-count: -1;
                }
            }
        }
        VerticalLayout {
            padding: 10px;
            alignment: start;
            y: 60px;
            spacing: 20px;
            VerticalLayout {
                alignment: start;
                spacing: 10px;
                SText {
                    horizontal-alignment: center;
                    min-width: 400px;
                    text: item.amount + " XDAG";
                    font-size: 30px;
                    font-weight: 600;
                    color: item.tranxType == TranxType.input ? ROOT_GLOBAL.greenColor : item.tranxType == TranxType.output ? ROOT_GLOBAL.textColorGray : ROOT_GLOBAL.mainColor54;
                }

                SText {
                    horizontal-alignment: center;
                    min-width: 400px;
                    text: snd-rec-on + " " + item.day + " " + item.time;
                    color: ROOT_GLOBAL.bottomNavColor;
                    font-size: 16px;
                }
            }

            if !WalletAccounts.block-refreshing && WalletAccounts.block-refreshed:VerticalLayout {
                alignment: start;
                spacing: 5px;
                Rectangle {
                // border-color: ROOT-GLOBAL.mainColor;
                border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: item.tranxType == TranxType.input ? i18n.sender : i18n.receiver;
                            font-size: 16px;
                        }

                        Rectangle { }

                        wlt-address := SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.current-block-info.address;
                            font-size: 16px;
                            font-weight: 600;
                        }

                        Rectangle {
                            width: 15px;
                        }

                        XButton {
                            font-size: 16px;
                            text: "";
                            height: 30px;
                            width: 30px;
                            icon: @image-url("../assets/content_copy.svg");
                            show-icon: true;
                            round: true;
                            clicked => {
                                copy-to(wlt-address.text);
                            }
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: "Hash";
                            font-size: 16px;
                        }

                        Rectangle { }

                        hash := SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.current-block-info.hash;
                            font-size: 14px;
                            font-weight: 600;
                        }

                        Rectangle {
                            width: 15px;
                        }

                        XButton {
                            font-size: 16px;
                            text: "";
                            height: 30px;
                            width: 30px;
                            icon: @image-url("../assets/content_copy.svg");
                            show-icon: true;
                            round: true;
                            clicked => {
                                copy-to(hash.text);
                            }
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: i18n.block_address;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: item.address;
                            font-size: 16px;
                            font-weight: 600;
                        }

                        Rectangle {
                            width: 15px;
                        }

                        XButton {
                            z: 222;
                            font-size: 16px;
                            text: "";
                            height: 30px;
                            width: 30px;
                            icon: @image-url("../assets/content_copy.svg");
                            show-icon: true;
                            round: true;
                            clicked => {
                                copy-to(item.address);
                            }
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: i18n.fee;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: WalletAccounts.current-block-info.fee + " XDAG";
                            font-size: 16px;
                            font-weight: 600;
                        }

                        Rectangle {
                            width: 15px;
                        }
                    }
                }

                Rectangle {
                    border-width: 1px;
                    background: ROOT_GLOBAL.blockColor;
                    border-radius: 8px;
                    HorizontalLayout {
                        padding: 8px;
                        SText {
                            min-width: 100px;
                            text: i18n.remark;
                            font-size: 16px;
                        }

                        Rectangle { }

                        SText {
                            horizontal-alignment: right;
                            min-width: 100px;
                            text: item.remark;
                            font-size: 16px;
                            font-weight: 600;
                        }

                        Rectangle {
                            width: 15px;
                        }
                    }
                }
            }
            if !WalletAccounts.block-refreshing && WalletAccounts.block-refreshed:HorizontalLayout {
                padding-top: 5px;
                padding-right: 20px;
                alignment: end;
                Button {
                    primary: true;
                    text: i18n.view_in_explorer;
                    clicked => {
                        WalletAccounts.open-in-browser(WalletAccounts.is-test,item.address);
                    }
                }
            }
        }
    }

    TouchArea {
        clicked => {
        }
    }
}
