import {Themes,PaddingType,ShadowType,BorderType} from "../../use/index.slint";
import {GlobalProps} from "./index.slint";

export global DefaultSDividerProps {
  //theme
  in-out property <Themes> theme: GlobalProps.theme;
    in-out property <length> height: 1px;
    in-out property <length> width: 100%;
    in-out property <PaddingType> padding-type:PaddingType.None;
    in-out property <ShadowType> shadow-type: ShadowType.High-empty;
    in-out property <BorderType> border-type: BorderType.None;
}
