import { AboutSlint } from "std-widgets.slint";
import {ROOT_GLOBAL} from "../global.slint";

export component About inherits Rectangle {
    width: 100%;
    height: 100%;
    background: ROOT-GLOBAL.bgColorMask-transparent;
    Rectangle {
        width: 400px;
        height: 300px;
        border-color: ROOT-GLOBAL.borderColor;
        border-width: 1px;
        background: ROOT-GLOBAL.bgColor;
        border-radius: 10px;
        VerticalLayout {
            alignment: center;
            AboutSlint { }
        }

        TouchArea {
            mouse-cursor: pointer;
            clicked => {
                root.visible = false;
            }
        }
    }
}
