import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { Themes } from "../modules/surrealism-ui/use/index.slint";
import { Button, HorizontalBox, LineEdit, CheckBox } from "std-widgets.slint";
import {I18n} from "../i18n.slint";
import {ROOT_GLOBAL, WalletAccounts, UiWallets} from "../global.slint";
import { XlineEdit } from "xline-edit.slint";

export component Contacts inherits Rectangle {
    in-out property <string> lang-name;
    in-out property <string> contact-name: "";
    in-out property <string> contatc-address: "";
    in property <bool> is-edit:false;
    callback close();
    callback action(string, string);
    border-color: ROOT-GLOBAL.borderColor;
    border-width: 1px;
    border-radius: 10px;
    background: ROOT-GLOBAL.bgColor;
    i18n := I18n {
        lang <=> lang-name;
    }

    SText {
        x: 8px;
        y: 10px;
        font-size: 20px;
        font-weight: 900;
        width: parent.width * 50%;
        text: is-edit ? i18n.edit_contact : i18n.add_contact;
    }

    top-bar := HorizontalBox {
        y: 0;
        width: 100%;
        height: 40px;
        alignment: end;
        XButton {
            font-size: 16px;
            text: "";
            height: parent.height * 70%;
            width: parent.height * 70%;
            icon: @image-url("../assets/close.svg");
            show-icon: true;
            round: true;
            clicked => {
                close();
            }
        }
    }

    SDivider {
        y: 50px;
        width: 100%;
    }

    VerticalLayout {
        width: 90%;
        alignment: center;
        Rectangle {
            height: 15%;
        }

        HorizontalBox {
            width: 100%;
            alignment: start;
            SText {
                font-size: 18px;
                font-weight: 600;
                width: parent.width * 50%;
                text: i18n.contact_name;
            }
        }

        Rectangle {
            height: 2%;
        }

        contact := XlineEdit {
            lang-name: lang-name;
            text: is-edit ? contact-name : "";
            font-size: 16px;
            height: 40px;
            placeholder-text: i18n.contact_name;
        }

        Rectangle {
            height: 5%;
        }

        HorizontalBox {
            width: 100%;
            alignment: start;
            SText {
                font-size: 18px;
                font-weight: 600;
                width: parent.width * 50%;
                text: i18n.walletAddress;
            }
        }

        Rectangle {
            height: 2%;
        }

        address := XlineEdit {
            lang-name: lang-name;
            text: is-edit ? contatc-address : "";
            font-size: 16px;
            height: 40px;
            placeholder-text: i18n.walletAddress;
        }

        Rectangle {
            height: 10%;
        }

        HorizontalBox {
            alignment: end;
            Button {
                primary: true;
                min-width: 100px;
                text: i18n.continueText;
                enabled: is-edit ? contact.text != contact-name || address.text != contatc-address : contact.text != "" && address.text != "";
                clicked => {
                    action(contact.text, address.text);
                    close();
                }
            }
        }
    }
}
