//! export components
//! you should export all components here
import { CreateWallet } from "./create-wallet.slint";
import { ImportWallet } from "./import.slint";
import { Contacts } from "./add-contact.slint";
import { Qrcode } from "./qrcode.slint";
import { MnemonicWin } from "./mnemonic.slint";
import { Transaction } from "./transaction.slint";
import {  XlineEdit } from "./xline-edit.slint";
import {  LanguageWin } from "./select-lang.slint";
import {  NetworkWin } from "./select-net.slint";
import {  SendWin } from "./send.slint";
import {  DelContact } from "./del-contact.slint";
import {  DelWallet } from "./del-wallet.slint";
import {  ErrorWin } from "./error.slint";



export {  CreateWallet,ImportWallet,Contacts,Qrcode,MnemonicWin,
    Transaction, XlineEdit,LanguageWin,NetworkWin,SendWin,DelContact,DelWallet,ErrorWin }
