import {ROOT_GLOBAL, WalletAccounts} from "../global.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import { SText } from "../modules/surrealism-ui/index.slint";
import {I18n, Language} from "../i18n.slint";


export component MnemonicWin inherits Rectangle {
    in-out property <string> lang-name;
    i18n := I18n {
        lang <=> lang-name;
    }

    callback close();
    callback copy-mnemonic();
    width: 100%;
    height: 100%;
    background: ROOT-GLOBAL.bgColorMask-transparent;
    Rectangle {
        z: 111;
        width: root.width * 50%;
        height: root.height * (WalletAccounts.current-mnemonic.length * 0.14 + 0.12);
        background: ROOT-GLOBAL.bgColor;
        border-color: ROOT-GLOBAL.borderColor;
        border-width: 1px;
        border-radius: 10px;
        HorizontalLayout {
            padding: 8px;
            y: 0;
            width: 100%;
            height: 60px;
            SText {
                min-width: 100px;
                text: i18n.mnemonic;
                font-size: 20px;
                font-weight: 900;
            }

            Rectangle { }

            XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 50%;
                width: parent.height * 50%;
                icon: @image-url("../assets/content_copy.svg");
                show-icon: true;
                round: true;
                clicked => {
                    copy-mnemonic();
                    close();
                }
            }

            Rectangle {
                width: 15px;
            }

            XButton {
                font-size: 16px;
                text: "";
                height: parent.height * 50%;
                width: parent.height * 50%;
                icon: @image-url("../assets/close.svg");
                show-icon: true;
                round: true;
                clicked => {
                    close();
                }
            }
        }

        VerticalLayout {
            padding: 10px;
            y: 60px;
            spacing: 20px;
            for line[i] in WalletAccounts.current-mnemonic: HorizontalLayout {
                spacing: 20px;
                for word[idx] in line: VerticalLayout {
                    height: 75px;
                    SText {
                        horizontal-alignment: center;
                        min-width: 100px;
                        text: i * 4 + idx + 1;
                        font-size: 16px;
                    }

                    Rectangle {
                        height: 40px;
                        border-color: ROOT-GLOBAL.mainColor;
                        border-width: 1px;
                        background: ROOT_GLOBAL.bgColorMask;
                        border-radius: 8px;
                        SText {
                            horizontal-alignment: center;
                            min-width: 100px;
                            text: word;
                            font-size: 18px;
                        }
                    }
                }
            }
        }
    }

    TouchArea {
        clicked => {
        }
    }
}
