import { SText, SDivider } from "../modules/surrealism-ui/index.slint";
import { XButton } from "../modules/surrealism-ui/x_index.slint";
import {  HorizontalBox } from "std-widgets.slint";
import {I18n,Language} from "../i18n.slint";
import {ROOT_GLOBAL,WalletAccounts} from "../global.slint";

export component NetworkWin inherits Rectangle {
    in-out property <string> lang-name;
    callback close();
    callback action(bool);
    i18n := I18n {
        lang <=> lang-name;
    }

    border-color: ROOT-GLOBAL.borderColor;
    border-width: 1px;
    background: ROOT-GLOBAL.bgColor;
    border-radius: 10px;
    SText {
        x: 8px;
        y: 10px;
        font-size: 20px;
        font-weight: 900;
        // width: parent.width * 50%;
        min-width: 300px;
        horizontal-alignment: left;
        text: i18n.select_network;
    }

    top-bar := HorizontalBox {
        y: 0;
        // width: 100%;
        height: 40px;
        alignment: end;
        XButton {
            font-size: 16px;
            text: "";
            height: parent.height * 70%;
            width: parent.height * 70%;
            icon: @image-url("../assets/close.svg");
            show-icon: true;
            round: true;
            clicked => {
                close();
            }
        }
    }

    SDivider {
        y: 50px;
        width: 100%;
    }

    VerticalLayout {
        padding-top: 10px;
        padding-left: 25px;
        padding-right: 25px;
        y: 70px;
        spacing: 20px;
        Rectangle {
            height: 50px;
            border-color: !WalletAccounts.is-test ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: !WalletAccounts.is-test ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "MainNet";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: !WalletAccounts.is-test ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    action(false);
                }
            }
        }

        Rectangle {
            height: 50px;
            border-color: WalletAccounts.is-test ? ROOT-GLOBAL.mainColor : ROOT-GLOBAL.blockColor;
            border-width: 1px;
            background: WalletAccounts.is-test ? ROOT_GLOBAL.bgColorMask : ROOT-GLOBAL.blockColor;
            border-radius: 8px;
            HorizontalBox {
                SText {
                    min-width: 100px;
                    text: "TestNet";
                    font-size: 18px;
                }

                Rectangle { }

                Image {
                    source: WalletAccounts.is-test ? @image-url("../assets/check_circle.svg") : @image-url("../assets/circle.svg");
                    colorize: ROOT_GLOBAL.mainColor;
                }
            }

            TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    action(true);
                }
            }
        }
    }
}
